INSERT INTO `rex_yform_field` (`table_name`, `prio`, `type_id`, `type_name`, `db_type`, `list_hidden`, `search`, `name`, `label`, `not_required`, `options`, `multiple`, `default`, `size`, `only_empty`, `message`, `table`, `field`, `type`, `empty_option`, `types`, `fields`, `address`, `width`, `height`, `attributes`, `preview`, `category`, `values`, `format`, `show_value`, `html`, `notice`, `rules`, `script`, `hashname`, `password_hash`, `no_db`, `password_label`, `empty_value`, `max_size`, `position`, `regex`, `pattern`, `current_date`, `widget`, `query`, `year_start`, `year_end`, `nonce_key`, `nonce_referer`, `sizes`, `messages`, `rules_message`, `choices`, `precision`, `unit`, `scale`)
VALUES
  ('rex_kunden_rechnungen',1,'value','datestamp','datetime',0,1,'datestamp','Zeitstempel','','','','','','0','','','','','','','','','','','','','','','Y-m-d H:i:s','0','','','','','','','0','','','','','','','','','','','','','','','','','','','',''),
  ('rex_kunden_rechnungen',2,'value','text','varchar(191)',0,1,'billnumber','Rechnungs-Nr.','','','','','','','','','','','','','','','','',' {\"placeholder\":\"Rechnungsnummer\"}','','','','','','','','','','','','0','','','','','','','','','','','','','','','','','','','',''),
  ('rex_kunden_rechnungen',3,'value','integer','int',0,1,'ordernumber','Auftrag Nr.','','','','','','','','','','','','','','','','','','','','','','','','','','','','','0','','','','','','','','','','','','','','','','','','','',''),
  ('rex_kunden_rechnungen',4,'value','choice','text',1,1,'costumernumber','Kunden-Nr.','','','0','','','','','','','','','','','','','','','','','','','','','','','','','','0','','','','','','','','','','','','','','','','','SELECT id AS value, customernumber AS label FROM rex_kunden','','','auswählen'),
  ('rex_kunden_rechnungen',5,'value','date','date',0,1,'date','Datum','','','','','','','','','','','','','','','','','{\"placeholder\":\"Rechnungsdatum\"}','','','','YYYY-MM-DD','','','','','','','','0','','','','','','','1','select','','2019','','','','','','','','','',''),
  ('rex_kunden_rechnungen',6,'value','number','',0,1,'invoiceamount','Betrag','','','','0,00','','','','','','','','','','','','','','','','','','','','','','','','','0','','','','','','','','','','','','','','','','','','5','€','2'),
  ('rex_kunden_rechnungen',7,'value','textarea','text',0,1,'articles','Artikel','','','','','','','','','','','','','','','','','{\"placeholder\":\"Artikel\"}','','','','','','','','','','','','0','','','','','','','','','','','','','','','','','','','',''),
  ('rex_kunden_rechnungen',8,'value','textarea','text',0,1,'notes','Notizen','','','','','','','','','','','','','','','','','{\"placeholder\":\"Notizen\"}','','','','','','','','','','','','0','','','','','','','','','','','','','','','','','','','',''),
  ('rex_kunden_rechnungen',9,'value','choice','text',1,1,'status','Status','','','0','','','','','','','','','','','','','','','','','','','','','','','','','','0','','','','','','','','','','','','','','','','','','{\"noch nicht bezahlt\": \"0\", \"bereits bezahlt\": \"1\", \"Teilzahlung\": \"2\", \"angemahnt\": \"3\"}','','','');
