INSERT INTO `rex_yform_field` (`table_name`, `prio`, `type_id`, `type_name`, `db_type`, `list_hidden`, `search`, `name`, `label`, `not_required`, `options`, `multiple`, `default`, `size`, `only_empty`, `message`, `table`, `field`, `type`, `empty_option`, `types`, `fields`, `address`, `width`, `height`, `attributes`, `preview`, `category`, `values`, `format`, `show_value`, `html`, `notice`, `rules`, `script`, `hashname`, `password_hash`, `no_db`, `password_label`, `empty_value`, `max_size`, `position`, `regex`, `pattern`, `current_date`, `widget`, `query`, `year_start`, `year_end`, `nonce_key`, `nonce_referer`, `sizes`, `messages`, `rules_message`, `choices`, `prepend`, `precision`, `unit`, `scale`)
VALUES
  ('rex_kunden',1,'value','datestamp','datetime',0,1,'datestamp','Zeitstempel','','','','','','0','','','','','','','','','','','','','','','Y-m-d H:i:s','0','','','','','','','0','','','','','','','','','','','','','','','','','','','','',''),
  ('rex_kunden',2,'value','text','varchar(191)',0,1,'firstname','Vorname','','','','','','','','','','','','','','','','','{\"placeholder\":\"Vorname\"}','','','','','','','','','','','','0','','','','','','','','','','','','','','','','','','','','',''),
  ('rex_kunden',3,'value','text','varchar(191)',0,1,'name','Nach- / Firmenname','','','','','','','','','','','','','','','','','{\"placeholder\":\"Nachname oder Firmenname\"}','','','','','','','','','','','','0','','','','','','','','','','','','','','','','','','','','',''),
  ('rex_kunden',4,'value','choice','text',0,1,'salutation','Anrede','','','0','','','','','','','','','','','','','','','','','','','','','','','','','','0','','','','','','','','','','','','','','','','','{\"Frau\": \"Frau\", \"Herr\": \"Herr\", \"Firma\": \"Firma\"}','','','',''),
  ('rex_kunden',5,'value','choice','text',0,1,'title','Titel / Rechtsform','','','0','','','','','','','','','','','','','','','','','','','','','','','','','','0','','','','','','','','','','','','','','','','','{\"Einzelperson\": {\"Dr.\": \"Doktor\", \"Prof.\": \"Professor\", \"RA\": \"Rechtsanwalt\", \"Notar\": \"Notar\", \"Dipl.-Jur.\": \"Dipl.-Jur.\", \"Dipl.-Ing.\": \"Dipl.-Ing.\"}, \"Gesellschaft\": {\"AG\": \"Aktiengesellschaft\", \"GmbH\": \"Gesellschaft mit beschränkter Haftung\", \"OHG\": \"Offene Handelsgesellschaft\", \"KG\": \"Kommanditgesellschaft\", \"GmbH & Co. KG\": \"GmbH & Co. KG\", \"GbR\": \"Gesellschaft bürgerlichen Rechts\"}}','','','',''),
  ('rex_kunden',6,'value','text','varchar(191)',0,1,'street','Straße u. Haus-Nr.','','','','','','','','','','','','','','','','','{\"placeholder\":\"Straße und Hausnummer\"}','','','','','','','','','','','','0','','','','','','','','','','','','','','','','','','','','',''),
  ('rex_kunden',7,'value','text','varchar(191)',0,1,'postcode','PLZ','','','','','','','','','','','','','','','','','{\"placeholder\":\"Postleitzahl\"}','','','','','','','','','','','','0','','','','','','','','','','','','','','','','','','','','',''),
  ('rex_kunden',8,'value','text','varchar(191)',0,1,'city','Stadt','','','','','','','','','','','','','','','','','{\"placeholder\":\"Wohnort / Sitz\"}','','','','','','','','','','','','0','','','','','','','','','','','','','','','','','','','','',''),
  ('rex_kunden',9,'value','text','varchar(191)',0,1,'country','Land','','','','','','','','','','','','','','','','','{\"placeholder\":\"Land\"}','','','','','','','','','','','','0','','','','','','','','','','','','','','','','','','','','',''),
  ('rex_kunden',10,'value','text','varchar(191)',0,1,'phonenumber','Tel.','','','','','','','','','','','','','','','','','{\"placeholder\":\"Telefonnummer\"}','','','','','','','','','','','','0','','','','','','','','','','','','','','','','','','','','',''),
  ('rex_kunden',11,'value','email','varchar(191)',0,1,'email','E-Mail','','','','','','','','','','','','','','','','','{\"placeholder\":\"E-Mail-Adresse\"}','','','','','','','','','','','','0','','','','','','','','','','','','','','','','','','','','',''),
  ('rex_kunden',12,'value','text','varchar(191)',0,1,'customernumber','Kunden-Nr.','','','','','','','','','','','','','','','','','{\"placeholder\":\"Kundennummer\"}','','','','','','','','','','','','0','','','','','','','','','','','','','','','','','','','','',''),
  ('rex_kunden',13,'value','choice','text',0,1,'status','Status','','','0','','','','','','','','','','','','','','','','','','','','','','','','','','0','','','','','','','','','','','','','','','','','{\"Standard\": \"standard\", \"Premium\": \"premium\", \"Inaktiv\": \"inaktiv\", \"Deaktiviert\": \"deaktiviert\"}','','','',''),
  ('rex_kunden',14,'value','textarea','text',0,0,'remarks','Anmerkugnen','','','','','','','','','','','','','','','','','{\"placeholder\":\"Individuelle Anmerkungen\"}','','','','','','','','','','','','0','','','','','','','','','','','','','','','','','','','','',''),
  ('rex_kunden',15,'value','text','varchar(191)',1,0,'password','Kundenpasswort','','','','','','','','','','','','','','','','','{\"placeholder\":\"Kundenpasswort\"}','','','','','','','','','','','','0','','','','','','','','','','','','','','','','','','','','','');
